Repository DurgNomis-drol/ha_toyota, pull requests merged in 2021-11, with the labels that each got.

#78 Remove v from version string
  .github/scripts/update_manifest.py
Labels: bug

#79 Bumps mytoyota to 0.7.3
  custom_components/toyota/manifest.json
  poetry.lock
  pyproject.toml
Labels: bug, enhancement

#80 Second try at fixing #74
  custom_components/toyota/__init__.py
Labels: bug

#84 Disable locale check
  custom_components/toyota/__init__.py
  custom_components/toyota/config_flow.py
  custom_components/toyota/manifest.json
  poetry.lock
  pyproject.toml
Labels: bug

#85 Update README.md and info.md
  README.md
  info.md
Labels: documentation

#87 Bump mytoyota module to 0.7.5
  custom_components/toyota/manifest.json
  poetry.lock
  pyproject.toml
Labels: bug

#86 Mark sensors as diagnostic
  custom_components/toyota/binary_sensor.py
  custom_components/toyota/sensor.py
  pyproject.toml
Labels: enhancement

#89 Fix wrong attributes in defogger sensors
  custom_components/toyota/binary_sensor.py
Labels: bug
