Repository DurgNomis-drol/ha_toyota, pull requests merged in 2023-11, with the labels that each got.

#166 V2
  .github/workflows/linting.yml
  .github/workflows/release-drafter.yml
  .github/workflows/update-manifest.yml
  .github/workflows/validate.yml
  .gitignore
  .pre-commit-config.yaml
  README.md
  custom_components/toyota/__init__.py
  custom_components/toyota/binary_sensor.py
  custom_components/toyota/config_flow.py
  custom_components/toyota/const.py
  custom_components/toyota/device_tracker.py
  custom_components/toyota/entity.py
  custom_components/toyota/manifest.json
  custom_components/toyota/sensor.py
  custom_components/toyota/translations/ca.json
  custom_components/toyota/translations/da.json
  custom_components/toyota/translations/de.json
  custom_components/toyota/translations/en.json
  custom_components/toyota/translations/es.json
  custom_components/toyota/translations/fr.json
  custom_components/toyota/translations/nb.json
  custom_components/toyota/translations/nl.json
  custom_components/toyota/utils.py
  poetry.lock
  pyproject.toml
Labels: bug, breaking change

#167 Extend & improve workflows
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/dependabot.yml
  .github/labels.yml
  .github/workflows/labeler.yml
  poetry.lock
  pyproject.toml
Labels: enhancement

#172 fix: better spanish translations
  custom_components/toyota/translations/es.json
Labels: :speech_balloon: translation

#173 adjust german translation
  custom_components/toyota/translations/de.json
Labels: :speech_balloon: translation

#179 Update French translations
  custom_components/toyota/translations/fr.json
Labels: :speech_balloon: translation

#177 remove device_class from fuel_level sensors
  custom_components/toyota/sensor.py
Labels: :bug: bug

#178 Replace EntityDescription with BinarySensorEntityDescription
  custom_components/toyota/binary_sensor.py
Labels: :sparkles: enhancement

#182 Create codeql.yml
  .github/workflows/codeql.yml
Labels: :sparkles: enhancement
