Repository DurgNomis-drol/ha_toyota, pull requests merged in 2024-01, with the labels that each got.

#203 Update French translations
  custom_components/toyota/translations/fr.json
Labels: :speech_balloon: translation

#198 Use new mytoyota api endpoints
  README.md
  custom_components/toyota/__init__.py
  custom_components/toyota/binary_sensor.py
  custom_components/toyota/config_flow.py
  custom_components/toyota/const.py
  custom_components/toyota/device_tracker.py
  custom_components/toyota/entity.py
  custom_components/toyota/manifest.json
  custom_components/toyota/sensor.py
  custom_components/toyota/translations/ca.json
  custom_components/toyota/translations/da.json
  custom_components/toyota/translations/de.json
  custom_components/toyota/translations/en.json
  custom_components/toyota/translations/es.json
  custom_components/toyota/translations/fr.json
  custom_components/toyota/translations/nb.json
  custom_components/toyota/translations/nl.json
  custom_components/toyota/utils.py
  poetry.lock
  pyproject.toml
Labels: :bug: bug, :warning: breaking change, :rocket: feature

#215 Enhancement: Remove constants that are deprecated in HA 2025.1
  custom_components/toyota/device_tracker.py
  custom_components/toyota/sensor.py
Labels: :wrench: enhancement
